/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conexaoBanco;

import java.sql.Connection;

public class App {


    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
		
		
	CriarTabela.criarTabelaUsuarios(conexao);
	
	AtualizarUsuario.atualizarUsuario(conexao,2, "Pedro", "pedro@gmail.com");
	AtualizarUsuario.atualizarUsuario(conexao,3, "Matheus", "matheus@gmail.com");
	DeletarUsuario.deletarUsuario(conexao, 1);
	System.out.println(ListarUsuarios.listarUsuarios(conexao));
    }
}
